export async function requestTestToken(user: "user-a" | "user-free") {
  void user;
  throw new Error("local test tokens must be generated by backend test helpers");
}

export type { DashboardState, WatchlistState } from "./types";
